//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNETWebApp_EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CountryIso3 { get; set; }
        public string RegionCode { get; set; }
    }
}
